### ISSUE TITLE
Remove "color correction" from HUD elements.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#134]
To clarify: set the player color to 255 0 0 and notice how the color isn't exactly pure red. It's something along the lines of 255 64 64. Same with black. It's not black, it's very dark grey.

**Comment by MatthewTheGlutton** [comment]
This appears to be because GREENPXL, being colour 112 on the Doom palette, is not actually pure green.

In fact, looking at the values here http://zdoom.org/wiki/Palette it seems that that entire line is not pure green o_O

I'm going to just leave this for now because the only alternative is - proportionally - obscenely bloaty.

**Comment by Accensus** [comment]
Guess I'll make my own PLAYPAL and see if it helps. Not a fan of those greens anyway.
