### ISSUE TITLE
Add option/cvar to toggle key flatness.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#153]
The recent FLATSPRITE update actually made the keys harder to see, but I understand the technical reasons for the change, so I propose an option or just a cvar to switch between FLATSPRITE and WALLSPRITE.

**Comment by MatthewTheGlutton** [comment]
I think I'm just going to create brand new sprites where they're these little terminals that are really heavy or affixed to the ground, and you just use them like you tap a credit card...

**Comment by beatcrazed** [comment]
If the terminals are fixed to the ground then it'll be a lot harder to avoid teleporting keycard squads.

**Comment by MatthewTheGlutton** [comment]
Could be bug instead of feature then :V though the interaction distance would remain the same so it might not be any different

**Comment by beatcrazed** [comment]
On most maps it probably wouldn't matter. I recently played through Doom64 and its extra level packs recently, and they love to tie the teleporting to picking up the card or skull instead of crossing a line close to it.

We don't need to be able to avoid them necessarily, but being able to does help with playability in many cases.

**Comment by MatthewTheGlutton** [comment]
Addressed as of 4aacd500efbb73e48602235ff60b0a724cfb4363
