### ISSUE TITLE
Feature request: use strings as derp tags so that I can name my derps

### ISSUE THREAD

**Issue by ElonSatoshi** [MatthewTheGlutton/HideousDestructor#155]
For instance, if I had 3 derps and I wanted to name them Snap, Crackle, and Pop, or if I just had 1 derp and wanted to name it Sparky.

**Comment by MatthewTheGlutton** [comment]
As far as I'm aware NetworkProcess args are still ints, so this would require a total overhaul of how this works.

Even if I felt like doing that, though, it'd require yet another (fortunately noarchive) cvar fetch, and we'd need some special character the player has to remember in order to separate the bot's name from the commands.

I'm willing to do this for the loadouts since being able to do that at all is such a huge game-changer, but for a purely non-necessary aesthetic improvement I'm going to [no] this pending possible developments in the future that let us handle console inputs in more flexible ways (or retrieve raw input data but that seems unlikely).
