### ISSUE TITLE
Sound definition requests

### ISSUE THREAD

**Issue by caligari87** [MatthewTheGlutton/HideousDestructor#25]
a1337spy posted this request on Discord a while back, not sure if they're planned or not. Would be really helpful for soundmods.

- [ ] separate reload sound defs for the pistol
- [ ] separate boss fire sound def
- [ ] separate thunderbuster fire sound defs
- [ ] separate smg reload sound defs
- [ ] separate thunderbuster reload sound defs
- [ ] separate liberator reload sound defs
- [ ] separate vulc reload sound defs
- [ ] separate medikit sound defs
- [ ] seperate mag in and mag out sound defs for the liberator, vulk, zm66, pistol, and smg
- [ ] separate ssg distant fire sound defs
- [ ] separate boss load sound defs

**Comment by MatthewTheGlutton** [comment]
I can't really figure out how to go through this systematically (by the time I've gone from looking at this list, to the sndinfo, to the weapon definition, I've already forgotten what I'm looking for), but it seems I've caught most of these just going through and renaming stuff in the weapon states so far?

There's a couple in here too that I might still want to keep identical because the object being handled is the same type, but I can reconsider that later.
