### ISSUE TITLE
Cannot set loadout for multiple shotguns

### ISSUE THREAD

**Issue by Derpford** [MatthewTheGlutton/HideousDestructor#30]
With loadout code `HUN 2`, you start with one Hunter. This is a clear and obvious issue for fools like me who think they can Reaper their way through HD.

**Comment by MatthewTheGlutton** [comment]
Gotta do it as commas, because the amount number is already used for some settings.

I intend to expand the amount system in (possibly deluded) hopes of getting rid of the weapongivers which are a whole realm of headache on their own, so unless I've got some perfect solution around that using amounts here will not be happening.
