### ISSUE TITLE
Feature request: less dependency on Doom 2

### ISSUE THREAD

**Issue by ElonSatoshi** [MatthewTheGlutton/HideousDestructor#4]
It's probably tough work, but... I wish that this mod didn't need to draw so much graphics from Doom 2. I want to be able to run this in Freedoom without imps switching between imps and serpentipedes, and the freedoom shotgun becoming the doom shotgun when reloading. If this mod used freedoom-based graphics, or more original graphics, and just used its own graphics instead of the iwad's, you might even be able to put a free license on it.

**Comment by MatthewTheGlutton** [comment]
Gonna add my explanation for the "wontfix" here since who knows where that post is on that ZDoom forums thread:

While I'm sympathetic to this in principle, HD was always intended to be an addition, commentary and speculative fanfic to the original Doom IP with its concepts and characters and themes. Many of HD's mechanics (e.g., the super shotgun) are based specifically on the sprites in Doom and do not carry well over to what's depicted in Freedoom.

I don't even know what Freedoom's backstory is or how stable it will be going forward.

**Comment by ElonSatoshi** [comment]
You should remove the wontfix tag... you fixed it... hideous destructor works beautifully with freedoom now. 

You even made a freedoom-y medikit gun.

I am so happy. Thank you.
