### ISSUE TITLE
Feature Request: Incap Pistol/Revolver

### ISSUE THREAD

**Issue by Silentdarkness12** [MatthewTheGlutton/HideousDestructor#46]
As it stands right now, if you are in a firefight and you get incap'd, what is usually meant to be a soft failure state quite often turns into a hard failure state, since, by the time you're even remotely close to being able to get back up, the enemy has walked over to you and is kicking you to death. This isn't even remotely close to fun, having to basically sit around and wait for them to actually kill you. Having some sort of emergency recourse would be deeply appreciated. One idea would be to allow an incapped player to try and take out a pistol or a revolver to defend themselves with.

If an incapped player has the strength left to take out a frag grenade, work the pin and spoon, and all, then it's not very unreasonable that the player should be able to reach down for a sidearm, pull it out and make some sort of final last-ditch attempt to put down an advancing foe. For balance sake, it's fair to say that the pistol or revolver isn't reloadable in an incapped state, but this would add a bit more immersion to incap.

**Comment by MatthewTheGlutton** [comment]
As mentioned before, it's really supposed to be a you're-almost-dead sort of deal - a state that in most FPSes would already be past game-over because the target is no longer a reasonable threat.

I might increase the amount of fucked up you have to be before you go into incap, and maybe make it harder even to use grenades or stims.
