### ISSUE TITLE
Fix truncation warnings

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#52]
Need to have Developer Messages set to "Warnings" in the message options to see those. It's not a big deal, really. There aren't enough warnings to slow down loading. I think.

**Comment by MatthewTheGlutton** [comment]
Where? I've just tried putting in an arbitrary "int blah=0.1;" and I get a warning just fine, and I can't find any such warning in the option search anywhere.

**Comment by Accensus** [comment]
Run HD with `+set developer 2`

![image](https://user-images.githubusercontent.com/24256978/72210741-dc290200-34c8-11ea-8b45-2164d60aab64.png)

There's a lot more above these.

**Comment by MatthewTheGlutton** [comment]
"Resolved self-referencing texture by picking an older entry for..."
As far as I can see those are all intentional and will not be fixed.

I see no reason to fix any of these, if it just results in all of them taking an extra step to cast explicitly in the VM which I can't see being possibly faster or more efficient in any way whatsoever.

**Comment by MatthewTheGlutton** [comment]
Reopening this after Rachael confirmed the casting is done at compile and no "de-optimization" happens if I make these explicit: https://forum.zdoom.org/viewtopic.php?f=122&t=66936

**Comment by MatthewTheGlutton** [comment]
I'll think about whether it's worth dealing with the texture warnings. (probably not - they're not even orange)
