### ISSUE TITLE
Frag grenades sometimes do not go through teleporters

### ISSUE THREAD

**Issue by TwelveEyes** [MatthewTheGlutton/HideousDestructor#75]
It doesn't happen all the time, but occasionally frag grenades will not teleport when throw into a teleporter.

An easy map to test this on is Map 21 of Doom 2. The starting room has a teleport pad in it you can chuck grenades into.

**Comment by MatthewTheGlutton** [comment]
Sometimes something's in the way.

I'm not aware of any way to fix this that doesn't have some really awful side effects. (Used to be you could telefrag someone with a launched grenade - had to take that out when it turned out they would constantly telefrag your voodoo dolls resulting in an instant suicide while fighting in the teleporter maze in Evilution map30)
