### ISSUE TITLE
Invalid sound position/velocity.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#82]
![Screenshot_Doom_20200201_005407](https://user-images.githubusercontent.com/24256978/73580274-a5258b00-448d-11ea-8168-79028f10c181.png)
Was chucking grenades. This happened when the grenade exploded and hit an Arachnotron (and probably whatever else was in the area). No reliable way to reproduce. Happens randomly. It's happened before too. Not sure why I didn't report it then.

**Comment by MatthewTheGlutton** [comment]
Almost willing to bet real money without even looking at the code there's a length() being called for a distance of (0,0,0)...

**Comment by MatthewTheGlutton** [comment]
I think I've taken care of all the zero-length vector.unit() calls.

The only thing I could see that would cause a different Z position treatment can't possibly be it, otherwise the error (or a VM abort) would be coming from the bullet or the archnotron.

I'll treat any new discoveries of this as a new problem and close this for now.
