### ISSUE TITLE
z6a is different from z66 nogl 1

### ISSUE THREAD

**Issue by boogiebogus** [MatthewTheGlutton/HideousDestructor#85]
using z66 nogl 1 to start results in having 49 bullets in your mag and 1 in the chamber, but z6a has 48 in the mag and 1 in the chamber

**Comment by MatthewTheGlutton** [comment]
I'm only going to try to fix this just in case it's a symptom of some other problem, but I think I'm going to phase out those codes (and hopefully eventually the weapongiver altogether)

**Comment by MatthewTheGlutton** [comment]
Turns out it's somehow calling loadoutconfigure() twice, and somehow the chamber flag is not set even though everything says it should be set.

This does not happen if you summon or give.

This makes no sense whatsoever and I don't have the ten months it'll take of going through the source code trying to piece out the logic of this.

I'll leave in the weapongiver actors but all loadout refids for them have been deleted.

(Next on todo list: allow something like `hd_give z66nogl` in place of this)
