### ISSUE TITLE
Possible healthbug

### ISSUE THREAD

**Issue by caligari87** [MatthewTheGlutton/HideousDestructor#9]
As of commit c4a3dbada927a24608090aa3de00b6838e41517b the player seems to have a soft buddha mode of sorts, where the last 10 HP are super-resilient, especially to bleeding. I've often been able to come back from 1 HP with _massive_ wounding as I simply don't bleed to death, and even getting shot without armor only knocks off 3-5 HP at low health when the same hits do 30-60 at full health.

**Comment by MatthewTheGlutton** [comment]
Where it happens with armour is definitely intentional. Without, I'm trying to err in favour of increasing structural damage on the player where eventually their systems irreparably fail, rather than dropping dead because their hitpoints ran out. I'm not sure if the current balance is appropriate but I prefer it over the instant lethality of what went on before.
