### ISSUE TITLE
Add visual indicator on HUD when weapon is braced.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#92]
Sound cue is barely audible unless mod is played without music and if there's not much going on in-game. In fact, I've been playing all the time for over a month now and didn't know that was a thing until someone on Discord told me.

**Comment by MatthewTheGlutton** [comment]
You have no idea how much I've gone out of my way specifically to avoid this.

**Comment by caligari87** [comment]
There's already also a visual cue as well, the gun does a little jerk along with the click. Also, when the gun is braced (+ I think holding the zoom/focus button) the player turns around the brace point instead of the player's center.

The key is getting to know the valid bracing conditions and watching for the secondary effects.

**Comment by Accensus** [comment]
Didn't know about the visual cue. Well, works for me! As long as I don't have to rely on sound...
